---
#
# @author Bodo (Hugo) Barwich
# @version 2021-08-02
# @package RPM Packaging for Perl
# @subpackage roles/module-spec/tasks/parse_package.yml

# This playbook executes the Package Configuration Parsing 
# from the downloaded Sources 
#
#---------------------------------
# Requirements:
#
#---------------------------------
# Configurations:
#
#---------------------------------
# External Parameters:
# - "list_packages": Dictionary of Found Packages
#




- name: Parse Package Source Configurations
  command:
    cmd: "roles/module-spec/library/parse_dependencies.pl -p=\"{{ package_data.package }}\" -r=\"{{ package_data.directory }}\" --dir=\"{{ source_directory }}\""
    warn: false
  changed_when: false
  loop: "{{ list_packages | dict2items }}"
  loop_control:
    loop_var: package_data
  register: package_dependency_rs
