---
abstract: 'Perl extension for using OpenSSL'
author:
  - 'Sampo Kellomäki <sampo@iki.fi>'
  - 'Florian Ragwitz <rafl@debian.org>'
  - 'Mike McCauley <mikem@airspayce.com>'
  - 'Chris Novakovic <chris@chrisn.me.uk>'
  - 'Tuure Vartiainen <vartiait@radiatorsoftware.com>'
  - 'Heikki Vatiainen <hvn@radiatorsoftware.com>'
build_requires:
  Carp: '0'
  Config: '0'
  Cwd: '0'
  English: '0'
  ExtUtils::MakeMaker: '0'
  File::Basename: '0'
  File::Spec::Functions: '0'
  Scalar::Util: '0'
  SelectSaver: '0'
  Socket: '0'
  Storable: '0'
  Test::More: 0.60_01
  base: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-SSLeay
no_index:
  directory:
    - t
    - inc
    - helper_script
    - examples
requires:
  MIME::Base64: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/radiator-software/p5-net-ssleay/issues
  repository: git://github.com/radiator-software/p5-net-ssleay.git
version: '1.90'
x_serialization_backend: 'CPAN::Meta::YAML version 0.012'
